# Generated by Django 4.2 on 2025-01-27 23:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
        ('posts', '0002_rename_post_artpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='artpost',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='art_posts', to='categories.category'),
        ),
    ]
