# Generated by Django 4.2 on 2025-03-10 21:37

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_artpost_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artpost',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, default='../default_post_tx8nvq', max_length=255, verbose_name='image'),
        ),
    ]
