# Generated by Django 4.2 on 2025-03-10 22:27

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_alter_artpost_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artpost',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
