# Generated by Django 4.2 on 2025-03-10 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_alter_artpost_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artpost',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
