# Generated by Django 4.2 on 2025-03-12 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('likes', '0002_commentlike'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CommentLike',
        ),
    ]
