# Generated by Django 4.2 on 2025-01-29 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('likes', '0002_remove_like_unique_like_like_unique_like'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='like',
            name='unique_like',
        ),
        migrations.AddConstraint(
            model_name='like',
            constraint=models.UniqueConstraint(fields=('owner', 'post'), name='unique_like'),
        ),
    ]
