# Generated by Django 4.2 on 2025-01-29 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_alter_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('portrait', 'Portrait'), ('landscape', 'Landscape'), ('abstract', 'Abstract'), ('still_life', 'Still Life')], default='Landscape', max_length=50, unique=True),
        ),
    ]
